use_frameworks!
platform :ios,'16.0'
inhibit_all_warnings!
post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
       end
    end
  end
end

target 'JXBanner_Example' do
  pod 'JXBanner', :path => '../'
#  pod 'JXBanner'
  pod 'SnapKit'

end
